version: '3.8'

services:
  # Redis for Celery broker and result backend
  redis:
    image: redis:7-alpine
    container_name: signal-noise-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: PostgreSQL for production (uncomment if needed)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: signal-noise-postgres
  #   environment:
  #     POSTGRES_DB: signal_noise
  #     POSTGRES_USER: signal_user
  #     POSTGRES_PASSWORD: signal_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U signal_user -d signal_noise"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # Optional: Neo4j (if not using external instance)
  # neo4j:
  #   image: neo4j:5.15-community
  #   container_name: signal-noise-neo4j
  #   environment:
  #     - NEO4J_AUTH=neo4j/signal_password
  #     - NEO4J_PLUGINS=["apoc", "graph-data-science"]
  #     - NEO4J_apoc_export_file_enabled=true
  #     - NEO4J_apoc_import_file_enabled=true
  #     - NEO4J_apoc_import_file_use__neo4j__config=true
  #     - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
  #     - NEO4J_dbms_memory_heap_initial__size=1G
  #     - NEO4J_dbms_memory_heap_max__size=2G
  #     - NEO4J_dbms_memory_pagecache_size=512M
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   volumes:
  #     - neo4j_data:/data
  #     - neo4j_logs:/logs
  #     - neo4j_import:/var/lib/neo4j/import
  #     - neo4j_plugins:/plugins
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "signal_password", "RETURN 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

volumes:
  redis_data:
    driver: local
  # postgres_data:
  #   driver: local
  # neo4j_data:
  #   driver: local
  # neo4j_logs:
  #   driver: local
  # neo4j_import:
  #   driver: local
  # neo4j_plugins:
  #   driver: local

networks:
  default:
    name: signal-noise-network
