#!/usr/bin/env python3
"""
Generate Entity Dossier for Arsenal FC
"""

import asyncio
import sys
import os
import json
from datetime import datetime
from pathlib import Path

# Load environment variables from project root
from dotenv import load_dotenv
project_root = Path(__file__).parent.parent
load_dotenv(project_root / '.env')

# Add backend to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from claude_client import ClaudeClient
from dossier_generator import EntityDossierGenerator


async def main():
    """Generate dossier for Arsenal FC"""

    print("\n" + "=" * 70)
    print("GENERATING ENTITY DOSSIER: ARSENAL FC")
    print("=" * 70)

    # Initialize
    client = ClaudeClient()
    generator = EntityDossierGenerator(client)

    # Arsenal FC details
    entity_id = "arsenal-fc"
    entity_name = "Arsenal FC"
    entity_type = "CLUB"
    priority_score = 99  # PREMIUM tier (11 sections with full analysis)

    print(f"\nEntity: {entity_name}")
    print(f"Entity ID: {entity_id}")
    print(f"Type: {entity_type}")
    print(f"Priority Score: {priority_score}")
    print(f"Expected Tier: PREMIUM (11 sections)")
    print(f"\nGenerating dossier...")

    # Generate dossier
    dossier = await generator.generate_dossier(
        entity_id=entity_id,
        entity_name=entity_name,
        entity_type=entity_type,
        priority_score=priority_score
    )

    # Display results
    print("\n" + "=" * 70)
    print("DOSSIER GENERATED SUCCESSFULLY")
    print("=" * 70)

    print(f"\n📊 Dossier Summary:")
    print(f"   Entity: {dossier.entity_name}")
    print(f"   Tier: {dossier.tier}")
    print(f"   Sections: {len(dossier.sections)}")
    print(f"   Generation Time: {dossier.generation_time_seconds:.2f} seconds")
    print(f"   Total Cost: ${dossier.total_cost_usd:.4f}")
    print(f"   Generated At: {dossier.generated_at.strftime('%Y-%m-%d %H:%M:%S')}")

    # Save to file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"arsenal-fc_dossier_{timestamp}.md"
    filepath = Path('data/dossiers') / filename
    filepath.parent.mkdir(exist_ok=True)

    with open(filepath, 'w') as f:
        f.write(f"# {dossier.entity_name} - Entity Dossier\n\n")
        f.write(f"**Generated**: {dossier.generated_at.strftime('%Y-%m-%d %H:%M:%S')} UTC\n")
        f.write(f"**Tier**: {dossier.tier}\n")
        f.write(f"**Sections**: {len(dossier.sections)}\n")
        f.write(f"**Generation Time**: {dossier.generation_time_seconds:.2f}s\n")
        f.write(f"**Total Cost**: ${dossier.total_cost_usd:.4f}\n\n")
        f.write("---\n\n")

        for section in dossier.sections:
            f.write(f"## {section.title}\n\n")
            f.write(f"**Generated By**: {section.generated_by.upper()}\n")
            f.write(f"**Confidence**: {section.confidence:.2f}\n\n")

            if section.metrics:
                f.write("### Metrics\n\n")
                for metric in section.metrics:
                    f.write(f"- **{metric.get('label', 'N/A')}**: {metric.get('value', 'N/A')}\n")
                f.write("\n")

            if section.content:
                f.write("### Details\n\n")
                for i, item in enumerate(section.content, 1):
                    f.write(f"{i}. {item}\n")
                f.write("\n")

            if section.insights:
                f.write("### Insights\n\n")
                for insight in section.insights:
                    f.write(f"- **{insight.get('category', 'N/A')}**: {insight.get('text', 'N/A')}\n")
                f.write("\n")

            if section.recommendations:
                f.write("### Recommendations\n\n")
                for rec in section.recommendations:
                    f.write(f"- **{rec.get('priority', 'N/A')}**: {rec.get('action', 'N/A')}\n")
                f.write("\n")

            f.write("---\n\n")

    print(f"\n💾 Dossier saved to: {filepath}")

    # Display sections preview
    print("\n" + "=" * 70)
    print("SECTIONS OVERVIEW")
    print("=" * 70)

    for i, section in enumerate(dossier.sections, 1):
        print(f"\n{i}. {section.title}")
        print(f"   Model: {section.generated_by.upper()}")
        print(f"   Confidence: {section.confidence:.2f}")
        print(f"   Content Items: {len(section.content)}")

        if section.content and len(section.content) > 0:
            preview = section.content[0][:100]
            print(f"   Preview: {preview}{'...' if len(preview) >= 100 else ''}")

        if section.metrics:
            print(f"   Metrics: {len(section.metrics)} metrics")

    # Display first section in detail
    print("\n" + "=" * 70)
    print("FIRST SECTION - FULL CONTENT")
    print("=" * 70)

    if dossier.sections:
        section = dossier.sections[0]
        print(f"\n## {section.title}\n")
        print(f"Generated By: {section.generated_by.upper()}")
        print(f"Confidence: {section.confidence:.2f}\n")

        if section.metrics:
            print("### Metrics")
            for metric in section.metrics:
                print(f"- {metric.get('label', 'N/A')}: {metric.get('value', 'N/A')}")
            print()

        print("### Details")
        for i, item in enumerate(section.content, 1):
            print(f"{i}. {item}")

    print("\n" + "=" * 70)
    print("DOSSIER GENERATION COMPLETE")
    print("=" * 70)

    return dossier


if __name__ == "__main__":
    import logging

    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    result = asyncio.run(main())
    exit(0 if result else 1)
