#!/usr/bin/env python3
"""
Generate a single dossier to verify integration is working
"""

import asyncio
import sys
import os
from datetime import datetime
from pathlib import Path

# Load environment variables from project root
from dotenv import load_dotenv
project_root = Path(__file__).parent.parent
load_dotenv(project_root / '.env')

# Add backend to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from claude_client import ClaudeClient
from dossier_generator import EntityDossierGenerator


async def main():
    """Generate a dossier and show the results"""

    print("\n" + "=" * 70)
    print("GENERATING TEST DOSSIER WITH CURRENT INTEGRATION")
    print("=" * 70)

    # Initialize
    client = ClaudeClient()
    generator = EntityDossierGenerator(client)

    # Generate dossier
    entity_id = "test-entity-1"
    entity_name = "Test Sports Club"
    entity_type = "CLUB"
    priority_score = 50  # STANDARD tier (7 sections)

    print(f"\nGenerating dossier for: {entity_name}")
    print(f"Entity ID: {entity_id}")
    print(f"Type: {entity_type}")
    print(f"Priority Score: {priority_score} (STANDARD tier)")

    dossier = await generator.generate_dossier(
        entity_id=entity_id,
        entity_name=entity_name,
        entity_type=entity_type,
        priority_score=priority_score
    )

    # Show results
    print("\n" + "=" * 70)
    print("DOSSIER GENERATED SUCCESSFULLY")
    print("=" * 70)

    print(f"\nEntity: {dossier.entity_name}")
    print(f"Tier: {dossier.tier}")
    print(f"Sections: {len(dossier.sections)}")
    print(f"Generation Time: {dossier.generation_time_seconds:.2f}s")
    print(f"Total Cost: ${dossier.total_cost_usd:.4f}")
    print(f"Generated At: {dossier.generated_at}")

    # Show first 3 sections
    print("\n" + "-" * 70)
    print("FIRST 3 SECTIONS:")
    print("-" * 70)

    for i, section in enumerate(dossier.sections[:3], 1):
        print(f"\n{i}. {section.title}")
        print(f"   Generated By: {section.generated_by.upper()}")
        print(f"   Confidence: {section.confidence:.2f}")
        print(f"   Content Items: {len(section.content)}")
        if section.content:
            print(f"   First Item: {section.content[0][:100]}...")

    # Check if fallback placeholders are present
    print("\n" + "-" * 70)
    print("FALLBACK PLACEHOLDER CHECK:")
    print("-" * 70)

    has_fallbacks = False
    for section in dossier.sections:
        for item in section.content:
            if "N/A" in item or "[year if available]" in item or "[name" in item:
                has_fallbacks = True
                break

    if has_fallbacks:
        print("✅ Fallback placeholders detected (expected when FalkorDB unavailable)")
    else:
        print("ℹ️  No fallback placeholders found (FalkorDB may be available)")

    print("\n" + "=" * 70)
    print("TEST COMPLETE")
    print("=" * 70)

    return dossier


if __name__ == "__main__":
    import logging

    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    result = asyncio.run(main())
    exit(0 if result else 1)
