#!/bin/bash
# ==============================================================================
# Run Outcome Tracking Migration via Supabase Dashboard
# ==============================================================================
# This script provides the exact steps to run the migration manually
# ==============================================================================

PROJECT_REF="itlcuazbybqlkicsaola"
DASHBOARD_URL="https://supabase.com/dashboard/project/${PROJECT_REF}"
SQL_EDITOR_URL="${DASHBOARD_URL}/sql/new"

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Outcome Tracking Migration - Supabase                          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Migration file: migrations/add_outcome_tracking.sql"
echo ""
echo "To run this migration, you have two options:"
echo ""
echo "═══ OPTION 1: Supabase Dashboard (Recommended) ═══"
echo ""
echo "1. Open this URL in your browser:"
echo "   ${SQL_EDITOR_URL}"
echo ""
echo "2. Copy and paste the contents of migrations/add_outcome_tracking.sql"
echo ""
echo "3. Click 'Run' to execute the migration"
echo ""
echo "═══ OPTION 2: Using psql ═══"
echo ""
echo "1. Get your database password from:"
echo "   ${DASHBOARD_URL}/settings/database"
echo ""
echo "2. Then run:"
echo ""
echo "   psql \"postgresql://postgres.[YOUR-PASSWORD]@db.${PROJECT_REF}.supabase.co:5432/postgres\" \\"
echo "       -f migrations/add_outcome_tracking.sql"
echo ""
echo "═══ What the migration creates ═══"
echo ""
echo "✅ Table: rfp_outcomes"
echo "   - Tracks RFP lifecycle and outcomes"
echo "   - Fields: id, rfp_id, entity_id, entity_name, status, stage, probability,"
echo "     value_estimated, value_actual, outcome_date, loss_reason, etc."
echo ""
echo "✅ Table: outcome_feedback_queue"
echo "   - Queue for batch processing of outcome feedback"
echo ""
echo "✅ View: rfp_outcome_summary"
echo "   - Aggregated performance metrics by entity"
echo ""
echo "✅ Function: update_entity_intelligence_from_outcome()"
echo "   - Updates entity intelligence scores based on RFP outcomes"
echo "   - WON → +10 intelligence score"
echo "   - LOST → -5 intelligence score"
echo ""
echo "✅ Function: record_outcome_feedback(p_rfp_id, p_entity_id, ...)"
echo "   - Helper function to record outcomes with automatic score updates"
echo ""
echo "✅ Trigger: outcome_feedback_loop"
echo "   - Fires on INSERT/UPDATE of rfp_outcomes"
echo "   - Automatically calls update_entity_intelligence_from_outcome()"
echo ""
echo "═══ Verification ═══"
echo ""
echo "After running the migration, verify with:"
echo ""
echo "   -- Check tables were created"
echo "   SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
echo "     AND tablename IN ('rfp_outcomes', 'outcome_feedback_queue');"
echo ""
echo "   -- Check the view was created"
echo "   SELECT viewname FROM pg_views WHERE schemaname = 'public'"
echo "     AND viewname = 'rfp_outcome_summary';"
echo ""
echo "═══ Quick Test ═══"
echo ""
echo "After migration, test the feedback loop:"
echo ""
echo "   -- Record a test win"
echo "   SELECT record_outcome_feedback("
echo "     'test-rfp-001',"
echo "     'test-entity',"
echo "     'Test Entity',"
echo "     'won',"
echo "     50000"
echo "   );"
echo ""
echo "   -- Check the outcome was recorded"
echo "   SELECT * FROM rfp_outcomes WHERE rfp_id = 'test-rfp-001';"
echo ""
echo "═══ ═══"
echo ""
